### ISSUE TITLE
Feature request : 점심시간을 강조하는 기능 요청

### ISSUE THREAD

**Issue by SpookyJelly** [naramdash/sandglass#1]
직장인의 가장 큰 즐거운인 점심시간은 SANDGLASS 앱에서 강조 될 필요가 충분히 있다고 생각합니다
해당 시간대의 background를 다른 색상으로 보여주든지, 아니면 해당 시간 10분전부터는 다른 색상으로 sand가 채워지든지 하는 기능을 요청합니다

**Comment by naramdash** [comment]
![image](https://github.com/naramdash/sandglass/assets/24370799/16600b2a-6e8e-4abf-81a1-8da2f941ee07)

issue over
